#Folders
INPUT_FOLDER = 'input'
OUTPUT_FOLDER = 'output'
NETWORK_FOLDER = 'network'

#Image
IMAGE_SIZE = 32
COLORED = False

#Network
BATCH_SIZE = 64
INPUT_SIZE = 128

#Generator
GEN_HIDDEN_LAYERS = 3
GEN_DROPOUT = 0.3

#Discriminator
DIS_CONVOLUTIONAL_LAYERS = [32, 64]
DIS_HIDDEN_LAYERS = 2
DIS_DROPOUT = 0.5
DISCRIMINATOR = None
DISCRIMINATOR.HIDDEN_LAYERS = 2
